import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { calculateBill, selectRate, winterAllowanceKgal, type RatePeriod, type ReadPeriod } from '../src/engine/billing'
import { buildData } from '../scripts/build-data'
import { reconcileAll, renderReport } from '../scripts/reconcile'

const data = buildData()
const rates = data.rates as unknown as RatePeriod[]
const periods = (m: string) => data.billingPeriods[m].rows as ReadPeriod[]

describe('winterAllowanceKgal', () => {
  const p: ReadPeriod[] = [
    { start: '2024-11-13', end: '2024-12-12', usage: 235 },
    { start: '2024-12-13', end: '2025-01-13', usage: 122 },
    { start: '2025-01-14', end: '2025-02-12', usage: 116 },
  ]
  it('averages Dec, Jan, Feb, rounds to the nearest thousand, and subtracts the included amount', () => {
    // (235 + 122 + 116) / 3 = 157.67 -> 158 - 3 = 155
    expect(winterAllowanceKgal(p, '2025-08-13', 3)).toBe(155)
  })
  it('uses the previous winter for periods ending in January and February', () => {
    expect(winterAllowanceKgal(p, '2026-02-12', 3)).toBe(155)
    expect(winterAllowanceKgal(p, '2026-03-16', 3)).toBeNull() // needs winter 2026, which is not in this list
  })
  it('returns null when a winter month is missing instead of guessing', () => {
    expect(winterAllowanceKgal(p.slice(1), '2025-08-13', 3)).toBeNull()
  })
})

describe('selectRate', () => {
  it('picks the rate by read period end and leaves earlier periods unpriced', () => {
    expect(selectRate(rates, '2026-01-13')?.applies_from_period_end).toBe('2025-08-13')
    expect(selectRate(rates, '2026-02-12')?.applies_from_period_end).toBe('2026-02-12')
    expect(selectRate(rates, '2026-07-15')?.applies_from_period_end).toBe('2026-05-13')
    expect(selectRate(rates, '2025-07-15')).toBeNull()
  })
})

describe('calculateBill', () => {
  it('matches a hand calculation: meter-1, 575,000 gallons, read period ending 2026-06-14', () => {
    // Allowance: winter 2026 periods 104, 115, 159 -> avg 126 -> 123 above the included 3.
    // Usage: 123 x 5.95 = 731.85; (572 - 123) = 449 x 8.94 = 4,014.06; total 4,745.91.
    // Drought 572 x 0.08 = 45.76. Superfund 575 x 0.0065 = 3.7375 -> 3.74. Service 55.01.
    // Tax 8.29% x (55.01 + 4,745.91 + 45.76 + 3.74 = 4,850.42) = 402.10. Other fees 7.32.
    // Total 55.01 + 4,745.91 + 45.76 + 3.74 + 402.10 + 7.32 = 5,259.84.
    const r = calculateBill('meter-1', '2026-05-14', '2026-06-14', 575000, rates, periods('meter-1'))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.allowanceKgal).toBe(123)
    const item = (n: string) => r.lineItems.find((l) => l.name === n)?.amount
    expect(item('Service charge')).toBe(55.01)
    expect(item('Excess usage charge')).toBe(4745.91)
    expect(item('Water drought')).toBe(45.76)
    expect(item('Superfund charge')).toBe(3.74)
    expect(item('Total taxes')).toBe(402.1)
    expect(item('Other fees')).toBe(7.32)
    expect(r.total).toBe(5259.84)
  })

  it('charges nothing for usage within the included 3,000 gallons', () => {
    const r = calculateBill('meter-3', '2026-06-15', '2026-07-15', 3000, rates, periods('meter-3'))
    expect(r.ok && r.lineItems.find((l) => l.name === 'Excess usage charge')?.amount).toBe(0)
  })

  it('refuses to price a period with no rate', () => {
    const r = calculateBill('meter-1', '2024-06-14', '2024-07-15', 100000, rates, periods('meter-1'))
    expect(r).toEqual({ ok: false, reason: 'no rate covers a period ending 2024-07-15' })
  })
})

describe('reconciliation gate', () => {
  const r = reconcileAll(data)
  it('reconciles at least the required share of bills', () => {
    expect(r.total).toBeGreaterThanOrEqual(52)
    expect(r.ratePercent).toBeGreaterThanOrEqual(r.required)
  })
  it('explains every failure', () => {
    for (const c of r.checks.filter((x) => x.priced && !x.pass)) {
      expect(c.needsReview, c.id).toBe(true)
      expect(c.notes.length, c.id).toBeGreaterThan(20)
    }
  })
  it('has a current RECONCILIATION.md and matching bill status fields', () => {
    const onDisk = readFileSync(join(__dirname, '..', 'data', 'RECONCILIATION.md'), 'utf8')
    const strip = (s: string) => s.replace(/^Generated by .*$/m, '')
    expect(strip(onDisk)).toBe(strip(renderReport(r, 'x')))
    for (const c of r.checks) {
      const bill = data.bills.find((b) => b.id === c.id)
      expect(bill?.reconciled, c.id).toBe(!c.priced ? 'unpriced' : c.pass ? 'pass' : 'fail')
    }
  })
})
