import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildData } from './build-data'
import type { SiteData } from './site-data'
import { calculateBill, type RatePeriod } from '../src/engine/billing'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

export type BillCheck = {
  id: string
  meter: string
  billDate: string
  printed: number
  computed: number | null
  delta: number | null
  lineMismatches: string[]
  pass: boolean
  reason: string
  needsReview: boolean
  notes: string
}

const round2 = (x: number) => Math.round(x * 100) / 100

/** Charges caused by paying late. Rates do not predict them, so they are passed through: added to the computed total and not compared. */
export const PASS_THROUGH_LINES = new Set(['Late fee charge', 'Delinquent letter charge', 'Tax on late fee'])

export function reconcileAll(data: SiteData) {
  const cfg = data.config.site as { reconciliation: { tolerance_usd_per_bill: { value: number }; required_pass_rate_percent: { value: number }; line_item_tolerance_usd: { value: number } } }
  const tol = cfg.reconciliation.tolerance_usd_per_bill.value
  const lineTol = cfg.reconciliation.line_item_tolerance_usd.value
  const rates = data.rates as unknown as RatePeriod[]
  const checks: BillCheck[] = data.bills.map((b) => {
    const periods = data.billingPeriods[b.meter]?.rows ?? []
    const r = calculateBill(b.meter, b.period_start, b.period_end, b.gallons, rates, periods)
    const base = { id: b.id, meter: b.meter, billDate: b.bill_date, printed: b.printed_total, needsReview: b.needs_review, notes: b.notes }
    if (!r.ok) return { ...base, computed: null, delta: null, lineMismatches: [], pass: false, reason: r.reason }
    const lineMismatches: string[] = []
    const passThrough = b.lineItems.filter((l) => PASS_THROUGH_LINES.has(l.name)).reduce((s, l) => s + (l.amount ?? 0), 0)
    for (const printed of b.lineItems.filter((l) => !PASS_THROUGH_LINES.has(l.name))) {
      const name = printed.name === 'Total taxes' ? 'Total taxes' : printed.name
      const mine = r.lineItems.find((l) => l.name === name)
      if (!mine || printed.amount === null || Math.abs(mine.amount - printed.amount) > lineTol + 1e-9) {
        lineMismatches.push(`${printed.name}: printed ${printed.amount?.toFixed(2) ?? 'blank'}, computed ${mine ? mine.amount.toFixed(2) : 'none'}`)
      }
    }
    const computed = round2(r.total + passThrough)
    const delta = round2(computed - b.printed_total)
    const pass = Math.abs(delta) <= tol + 1e-9 && lineMismatches.length === 0
    const reason = pass ? 'Within tolerance' : Math.abs(delta) > tol ? `Total differs by ${delta.toFixed(2)}` : 'Line item mismatch'
    return { ...base, computed, delta, lineMismatches, pass, reason }
  })
  const passed = checks.filter((c) => c.pass).length
  const rate = checks.length ? (100 * passed) / checks.length : 0
  return { checks, passed, total: checks.length, ratePercent: rate, required: cfg.reconciliation.required_pass_rate_percent.value, tol, lineTol }
}

function money(n: number | null) {
  return n === null ? 'n/a' : n.toFixed(2)
}

export function renderReport(r: ReturnType<typeof reconcileAll>, builtOn: string): string {
  const failures = r.checks.filter((c) => !c.pass)
  const lines = [
    '# Bill reconciliation',
    '',
    `Generated by \`npm run reconcile\` on ${builtOn}. Do not edit by hand.`,
    '',
    `Each bill in \`data/bills/\` is recomputed from the rate files in \`data/rates/\` and the read-period usage in \`data/billing-periods/\`. A bill passes when its total is within $${r.tol.toFixed(2)} of the printed total and every line item is within $${r.lineTol.toFixed(2)}. Late fees and delinquent letter charges are not predicted by rates; they are added to the computed total as printed.`,
    '',
    `**${r.passed} of ${r.total} bills pass (${r.ratePercent.toFixed(1)}%). Required: ${r.required}%. ${r.ratePercent >= r.required ? 'Gate met.' : 'Gate NOT met.'}**`,
    '',
    'Important: the rate files were derived from these same bills, so passing shows the rate model is internally consistent with the bills. It is not an independent check against a published City of Mesa rate schedule. Confirm against the schedule when it is available.',
    '',
    '## Failures and explanations',
    '',
  ]
  if (failures.length === 0) lines.push('None.', '')
  for (const f of failures) {
    lines.push(`### ${f.id} (bill dated ${f.billDate})`, '', `Printed ${money(f.printed)}, computed ${money(f.computed)}, delta ${money(f.delta)}. ${f.reason}.`, '')
    for (const m of f.lineMismatches) lines.push(`* ${m}`)
    lines.push('', `Explanation: ${f.notes || 'NOT YET EXPLAINED.'}`, '')
  }
  lines.push('## All bills', '', '| Bill | Bill date | Printed total | Computed | Delta | Result |', '|---|---|---|---|---|---|')
  for (const c of r.checks) lines.push(`| ${c.id.replace('bills/', '')} | ${c.billDate} | ${money(c.printed)} | ${money(c.computed)} | ${money(c.delta)} | ${c.pass ? 'pass' : 'fail'} |`)
  lines.push('')
  return lines.join('\n')
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const data = buildData()
  const r = reconcileAll(data)
  writeFileSync(join(root, 'data/RECONCILIATION.md'), renderReport(r, new Date().toISOString().slice(0, 10)))
  for (const c of r.checks) {
    const path = join(root, 'data', `${c.id}.md`)
    const text = readFileSync(path, 'utf8')
    writeFileSync(path, text.replace(/^reconciled: (pending|pass|fail)$/m, `reconciled: ${c.pass ? 'pass' : 'fail'}`))
  }
  console.log(`reconcile: ${r.passed}/${r.total} pass (${r.ratePercent.toFixed(1)}%), required ${r.required}%`)
  for (const c of r.checks.filter((x) => !x.pass)) console.log(`  fail ${c.id}: ${c.reason}${c.lineMismatches.length ? ' | ' + c.lineMismatches.join('; ') : ''}`)
}
